import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Tajawal,
  Aref_Ruqaa_Ink,
  Cairo,
} from "next/font/google"; // edited: add Cairo
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "700", "800", "900"],
});

const arefRuqaaInk = Aref_Ruqaa_Ink({
  variable: "--font-aref-ruqaa-ink",
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
});

const cairo = Cairo({
  // edited: expose Cairo as CSS variable
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"], // edited: choose what you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable} ${arefRuqaaInk.variable} ${cairo.variable}`} // edited: add cairo var
      suppressHydrationWarning
    >
      {/* edited: use Tailwind's font-sans which we will map to Cairo-first stack */}
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
